name: Deploy production

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Redeploy App Platform
        run: doctl apps create-deployment ffa264d7-e897-4fe6-b0c5-67c605868398 --force-rebuild --wait
